### PR TITLE
Thermal Resistance Conversion Methods

### LINKED ISSUE #111: Add Thermal Resistance Conversion
#### Description
New methods used for converting thermal resistance (R-value) and thermal transmittance (U-value) between imperial units and metric units (ft2-h-F/Btu to m2K/W). This will be used in facade calculations for both thermal performance and embodied carbon.

### PR DESCRIPTION
**Pull request by vgreen-BH**
### Issues addressed by this PR

 Closes #111 

 
Adds new conversion methods to convert R-value and U-value between metric and imperial.

 ### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Facade_Engine/BHoM%20PR%20Test%20Files/240423_LocalisationToolkit_Thermal%20Resistance%20Test.gh?csf=1&web=1&e=xjr10t

 ### Additional comments

Required for Facade Embodied Carbon Toolkit

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Review by enarhi — APPROVED** [review]
LGTM, used test file and cross checked against conversion factor both ways and it is applied correctly.

**Comment by enarhi** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
