### PR TITLE
Adding ToUnit methods

### LINKED ISSUE #51: Units_Engine: provide ToUnit( quantity, unit ) and FromUnit( quantity, unit)
#### Description:

Methods ToUnit( double quantity, string unit ) and FromUnit( double quantity, string unit ), which would attempt to find a match for the input unit string, and use the corresponding convert method.

If a user provided "inch", "inches", "inch", we would call ToInch(), if a user provided "square inches", "in^2", "inch^2", etc. we call ToSquareInch(). This would allow convenient usage in spreadsheets where a list of properties and their units are provided, and the quantity is to be extracted and converted from several BHoM objects:
```
    A              B                 C                 D
1                  Height            Width             Area
2                  in                in                in^2
3 Object1          ToUnit(getProperty(A3, B1), B2)
4 Object2
```

### PR DESCRIPTION
**Pull request by JosefTaylor**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #51
Partially addresses [UI Issue 128](https://github.com/BHoM/BHoM_UI/issues/128)

 

 ### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Localisation_Toolkit/Units_Engine/%2376-Add%20ToUnit()%20and%20FromUnit()?csf=1&web=1&e=a4z6Ts

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
For string matching, could also check if the string is one of the enum names, to reduce number of strings we have to add to the switch-case.
I'd also thought about converting other enums (such as Midas, XML, other toolkits which have units enums) to strings, but the code wasn't super clean so I haven't yet.

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check project-compliance

**Comment by JosefTaylor** [comment]
copyright-compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check copyright-compliance

**Comment by JosefTaylor** [comment]
@BHoMBot fix copyright headers ref. 7324744578

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot fix copyright headers ref. 7324744578

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by michaelhoehn** [comment]
> @FraserGreenroyd I noticed BHoMBot started by adding new copyright headers with the date 2021, and then failed the test again and changed it to 2022; is this an issue with templates?

Looks like two separate functions are being called. One to add if missing, and one to uptick if incorrect. I'm loving the pair programming tho 😄 🤖 🤝

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check core

**Comment by JosefTaylor** [comment]
@BHoMBot check null-handling

**Comment by JosefTaylor** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd I noticed BHoMBot started by adding new copyright headers with the date 2021, and then failed the test again and changed it to 2022; is this an issue with templates?

@JosefTaylor [this PR](https://github.com/BHoM/BHoM/pull/1417) should fix this going forward. BHoMBot pulls that file to get the latest information, and it was erroneously missed from the updates in January, so it was pulling an out-of-date header, inserting it, then failing it because it's out-of-date, and then upticking it on the second pass, as these are 2 different functions called within the bot as @michaelhoehn correctly pointed out. Hopefully should be resolved now (for this year at least...) 😄

**Comment by JosefTaylor** [comment]
@BHoMBot check null-handling

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@BHoMBot check project-compliance

**Comment by JosefTaylor** [comment]
@BHoMBot fix project file ref. 7455435973

**Comment by JosefTaylor** [comment]
@BHoMBot check project-compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check project-compliance

**Comment by JosefTaylor** [comment]
Hey @FraserGreenroyd, I'm also having some issues with Project Compliance- one, it wants me on the csproj new format, which I'd love to have some help with, and two, it's complaining about the post-build, which I believe is OK- it might just be there's some white space it didn't understand.

**Comment by JosefTaylor** [comment]
@BHoMBot check-required

**Comment by JosefTaylor** [comment]
@michaelhoehn @peterjamesnugent would you mind reviewing? there's a nice big test script in the folder!

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@JosefTaylor no worries, I think there's some teething problems with the post build check, @vietle-bh has been having trouble too. I'll be looking into it soon!
For the new project style, we can do a small workshop on that maybe as a use-case later in the milestone with @travispotterBH and @alexissantella perhaps? 😄

**Comment by JosefTaylor** [comment]
@BHoMBot check copyright-compliance dataset-compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check dataset-compliance

**Comment by emidio-piermarini** [comment]
Reviewed and looks good for the ones which have had functionality

**Review by emidio-piermarini — APPROVED** [review]
Looks good for the ones that have functionality already.  Suggest that we raise an issue to get units which currently have not support done.

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Comment by JosefTaylor** [comment]
@FraserGreenroyd please merge if you're happy with it!

**Comment by JosefTaylor** [comment]
@emidio-piermarini agreed; it currently supports all the units we've done before with ToFoot() ToKilopoundForce() etc., which I believe more than covers the `QuantityType` attributes we've implemented, but there are many more compound units which could be added!
This also leaves room for adding nicknames to units, which could be done by anyone as needed

**Pull request merged**
