### PR TITLE
Add Force, ForcePerLength, Pressure, Area, Acceleration, Volume, AreaMomentOfInertia and Density conversion methods

### LINKED ISSUE #27: Add the following unit conversions: Force, ForcePerLength, Pressure, Area, Acceleration, Volume, AreaMomentOfInertia and Density
#### Description:

Add the following to `To` and `From` conversion units:

- [x] Force: Newton, kilogramforce, tonnesforce, kilonewton, meganewton, poundsforce, ounceforce, kilopoundforce (kips)
- [x] ForcePerLength Newtonpermetre, Newtonpermillimetre, kilogramforcepermetre, poundforceperfoot, poundforceperinch, poundforceperyard, kilipoundforceperfoot, 
- [x] Pressure Pascal, atmosphere, bar, kilogramforcepersquaremetre, kilogramforcepersqaurecentimeter, kilogramfrocepersquaremillimetre, newtonpersquaremetre, newtonpersquarecentimetre, newtonpersquaremillimetre, technicalatmosphere, poundforcepersquareinch, poundforcepersquarefoot, tonneforcepersquaremillimetre, tonneforcepersquaremetre, tonneforcepersqaurecentimetre
- [x] Area squaremetre, squarekilometre, squarecentimetre, squaremullimetre, squaremile, squareyard, squarefoot, squareinch, acre, hectare, squarenauticalmile
- [x] Acceleration metrepersecondsquared, inchpersecondsquared, footpersecondsqaured, standardgravity
- [x] Volume cubicmetre, litre, cubickilometre, cubiccentimetre, cubicmillimetre, cubicyard, cubicfoot, cubicinch, imperialgallon, usgallon, 
- [x] AreaMomentOfInertia metrefourth, centimetrefourth, millimetrefourth, footfourth, inchforth
- [x] Density

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

 Closes #27 

 

 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Er03Y8_R129Dp3GbXywo14EBB7PiVD7XFf60ZMmjWPEfaQ?e=foWYXx

 ### Changelog

 ### Additional Comments
The style I have been following (so the reviewers can check):
1. Method names should `To`/`From` + SingularUnit e.g. `ToYard` `FromYard`
2. Reference to units in input/output/description attributes should be plural i.e.:
`        [Input("yards", "The number of yards to convert")]`
`        [Output("yards", "The number of yards")]`
3. Capitalisation of a unit is only when it is without a prefix and is named after an individual e.g. "Newtons" and "kilonewtons"

@FraserGreenroyd @michaelhoehn @IsakNaslundBh it may be worth splitting up the reviewing to more manageable chunks:
- [ ] Acceleration
- [ ] Area
- [ ] Area Moment of Interia
- [ ] Density
- [ ] Force
- [ ] Force per length
- [ ] Pressure
- [ ] Volume

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@peterjamesnugent regarding your last commit you might want to see this discussion: https://github.com/BHoM/CarbonQueryDatabase_Toolkit/pull/25#discussion_r411204071

**Comment by peterjamesnugent** [comment]
> @peterjamesnugent regarding your last commit you might want to see this discussion: [BHoM/CarbonQueryDatabase_Toolkit#25 (comment)](https://github.com/BHoM/CarbonQueryDatabase_Toolkit/pull/25#discussion_r411204071)

Is that comment not referencing the description? 

Based on all the other quantities in this toolkit the the method name is To/From + singular unit e.g. `ToYard`and `FromYard`. If it was feet, then these would be `ToYards` and `FromYards`.

Then in the description, input/output attributes reference is made to the plural of the quantities:

**Comment by FraserGreenroyd** [comment]
Hmm you make a fair point. I guess that CQD one was based on what reads better (I know for me ToFoot just reads odd). Happy to go with singular for consistency if that's what you've implemented with the rest :smile:

**Comment by IsakNaslundBh** [comment]
> Capitalisation of a unit is only when it is without a prefix and is named after an individual e.g. "Newtons" and "kilonewtons"

is this right? I would assume ToKiloNewton and FromKiloNewton for this.. Personally think that reads better, and it is good to have the central unit (metre/Newton) always capitalised?

**Comment by peterjamesnugent** [comment]
> Capitalisation of a unit is only when it is without a prefix and is named after an individual e.g. "Newtons" and "kilonewtons"
> 
> is this right? I would assume ToKiloNewton and FromKiloNewton for this.. Personally think that reads better, and it is good to have the central unit (metre/Newton) always capitalised?

I don't agree, kilonewton is one word. ToCentiMetre looks off in my opinion. 

e.g. `ToKiloNewtonPerCentiMetreSquared `vs `ToKilonewtonPerCentimetreSquared`

**Comment by IsakNaslundBh** [comment]
> > Capitalisation of a unit is only when it is without a prefix and is named after an individual e.g. "Newtons" and "kilonewtons"
> > is this right? I would assume ToKiloNewton and FromKiloNewton for this.. Personally think that reads better, and it is good to have the central unit (metre/Newton) always capitalised?
> 
> I don't agree, kilonewton is one word. ToCentiMetre looks off in my opinion.
> 
> e.g. `ToKiloNewtonPerCentiMetreSquared `vs `ToKilonewtonPerCentimetreSquared`

Fair enough, you are the native English speaker after all (and noone else has raised it) 😃 

My only argument would be that the word stating the actual quantity you are working with is not capitalised in your example above, whilst all others are, and to a large extent those are the most important ones. 

But, again, ok with this being voted down!

**Pull request merged**
