### PR TITLE
Add unit tests

### LINKED ISSUE #54: Localisation_Toolkit: Add unit tests for convert methods
#### Definition of the test :
For each of the convert methods provide a unit test with single input value of 1 and single output of the converted value.

### PR DESCRIPTION
**Pull request by rolyhudson**
### Issues addressed by this PR

 Closes #54 
1 unit test for each Convert method created and added to .ci\Datasets\Convert

 ### Test files
[Test creation script.](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/Localisation_Toolkit/UnitTests/CreateConvertTests.gh?csf=1&web=1&e=JiWYVd)
[~~Test summary excel file.~~](https://burohappold.sharepoint.com/:x:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/Localisation_Toolkit/UnitTests/TestSummarySheet.xlsx?d=w7e235447cddd4e3e9a89f6e3303483a7&csf=1&web=1&e=8C0fdW)
No need for this excel file just confusing don't look at it.
[CheckTest](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/Localisation_Toolkit/UnitTests/Convert.gh?csf=1&web=1&e=hPNZDf) - Script to run CheckTest on the serialised set of unit tests.

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit tests

**Review by LMarkowski — APPROVED** [review]
In general looks very good to me. As mentioned during the stand-up I noticed that some of the UTs return difference since the beginning. 🤔 Let's see what will bhombot return.

image

Double ToNanometre(Double)
Double FromKilopoundForcePerSquareFoot(Double)
Double ToDeltaDegreeCelsius(Double)
Double FromDeltaDegreeCelsius(Double)
Double ToKilonewtonMillimetre(Double)
Double FromKilonewtonMillimetre(Double)
Double ToCubicInch(Double)
Double ToArcseconds(Double)
Double ToInchToTheFourth(Double)
Double ToInverseDeltaDegreeCelsius(Double)
Double FromInverseDeltaDegreeCelsius(Double)
Double ToGramPerLitre(Double)
Double FromGramPerLitre(Double)
Double FromTonnePerCubicCentimetre(Double)
Double FromPoundPerCubicInch(Double)

**Comment by rolyhudson** [comment]
Yes getting some Differences on my end too.

**Comment by LMarkowski** [comment]
image
BHoMBot seems to be disagreeing with us 😬

**Comment by rolyhudson** [comment]
Removed some nulls that were going in as output values. But I don't see why these results are considered a difference?
Screenshot 2020-12-10 093226

**Comment by LMarkowski** [comment]
@BHoMBot check unit tests

**Comment by rolyhudson** [comment]
@BHoMBot check unit tests

**Comment by rolyhudson** [comment]
@BHoMBot check unit tests

**Comment by rolyhudson** [comment]
@BHoMBot check unit tests

**Review by LMarkowski — APPROVED** [review]
Everything LGTM now! 🚀 
Sorry for the late review.

**Review by FraserGreenroyd — APPROVED** [review]
LGTM

**Pull request merged**
