### PR TITLE
Update to .netstandard2.0

### LINKED ISSUE #88: Upgrade to .NetStandard2.0
#### Description:

Update oM and Engine type of toolkit to .NetStandard2.0 to align with core

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #88

 

Upgrade to .netstandard 2.0 in alignment with other core

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check unit-tests

**Review by FraserGreenroyd — APPROVED** [review]
All checks have passed so happy to deploy.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
