### PR TITLE
Pluralise descriptions for Duration Converts

### LINKED ISSUE #100: Plurals used in Duration methods
#### Broken rules:

Does not follow the convention of the Localisation_Toolkit

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #100 

 

 ### Test files

By inspection

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
In line with the issue and as discussed on Teams, happy to merge.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: code-compliance, copyright-compliance, dataset-compliance, documentation-compliance, installer, null-handling, project-compliance, ready-to-merge, serialisation, versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Pull request merged**
