### PR TITLE
Fix the nuspec template file to reference the correct framework

### LINKED ISSUE #130: Fix the nuspec template file to reference the correct framework
#### Description:
See code here where the framework is set to `netstandard2.0.0` instead of `netstandard2.0`:
https://github.com/BHoM/Localisation_Toolkit/blob/e85a0a3658cc919d8a112afb907ca960763752b4/.ci/BHoMBot/Nuget/BHoM.Interop.Localisation.nuspec#L18

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

 Closes #130 

Fairly straightforward. I simply removed the extra `.0` in the target framework. So this should be pretty quick and easy to review.

 ### Test files

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Review by IsakNaslundBh — APPROVED** [review]
Approved by code inspection and happy with the change.

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
