### PR TITLE
Update UnitsNet to fix CoefficientOfThermalExpansion conversions

### LINKED ISSUE #80: Coefficient of Thermal Expansion is converted incorrectly
#### Description:

Coefficient of thermal expansion conversions appear to be inverted, see [Issue 807 on UnitsNet](https://github.com/angularsen/UnitsNet/issues/807)

This has already been fixed in UnitsNet and all that's needed on our end is to update the NuGet package.

### PR DESCRIPTION
**Pull request by JosefTaylor**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #80 

 

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-test

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by JosefTaylor** [comment]
image
Based on testing of the methods failing in unit-tests, I believe the test should be dispensated. The differences that bhom-bot shows other than inverse degrees are rounding errors.

**Comment by FraserGreenroyd** [comment]
Item 9, `35.314667` compared to `35.314725` isn't a rounding error - that's `0.000058` different. Whoever setup the unit test decided we need to go to 6dp - so question is, did the new UnitsNet introduce differences at that level of precision that didn't exist previously?

**Comment by IsakNaslundBh** [comment]
Did some quick digging on the UnitsNet repo, and 9 and 14 are for example handled by https://github.com/angularsen/UnitsNet/pull/1029 .

And the moment issues seem to stem from https://github.com/angularsen/UnitsNet/pull/1011

These are probably both improvements, but it needs to be validated, and if accepted, UnitTests ofc updated.

@FraserGreenroyd I assume this is ok to get merged in next sprint, given that it fixes the bug shown in item (1) in Josefs list?

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by JosefTaylor** [comment]
Doing some comparison with a user-calculated conversion based on official conversions and earth gravity:
image
The PR gives us better fidelity to the user calculation than the main branch

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Comment by JosefTaylor** [comment]
@FraserGreenroyd does this look good to you?

**Comment by IsakNaslundBh** [comment]
> Doing some comparison with a user-calculated conversion based on official conversions and earth gravity: image The PR gives us better fidelity to the user calculation than the main branch

Perfect @JosefTaylor .

With that, we just need to get the UnitTests updated, so they also reflect this change. Have sent you a script to help with this!

**Comment by JosefTaylor** [comment]
@BHoMBot check unit-tests

**Comment by JosefTaylor** [comment]
@BHoMBot check compliance

**Comment by JosefTaylor** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Have reviewed with the unit tests and discussion here, as well as an on Teams discussion with @JosefTaylor and am happy with the updates this PR is bringing from a code review and deployment perspective for the upcoming beta. Thanks for updating the unit tests following the review @JosefTaylor 😄

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: dataset-compliance

**Pull request merged**
