### PR TITLE
Fixing Unit test errors

### LINKED ISSUE #116: An error occurred on a unit test
<samp>The following errors have been reported on unit tests in this repository.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromAcre.json**
Unit test set: FromAcre. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromAcre(Double acres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:58:54
			Data returned for output 0 is different than expected.
			Expected value: 4046.85642, returned value from execution: 4046.8564224.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromKilogramForce.json**
Unit test set: FromKilogramForce. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromKilogramForce(Double kilogramsForce).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:58:56
			Data returned for output 0 is different than expected.
			Expected value: 9.80665002864, returned value from execution: 9.80665.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromKilopoundForce.json**
Unit test set: FromKilopoundForce. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromKilopoundForce(Double kilopoundsForce).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:58:56
			Data returned for output 0 is different than expected.
			Expected value: 4448.22161526051, returned value from execution: 4448.2216152605.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromMile.json**
Unit test set: FromMile. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromMile(Double miles).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:58:57
			Data returned for output 0 is different than expected.
			Expected value: 1609.34, returned value from execution: 1609.344.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromSquareMile.json**
Unit test set: FromSquareMile. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromSquareMile(Double squareMiles).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:58:57
			Data returned for output 0 is different than expected.
			Expected value: 2590000, returned value from execution: 2589988.110336.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromSquareYard.json**
Unit test set: FromSquareYard. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromSquareYard(Double squareYards).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:58:57
			Data returned for output 0 is different than expected.
			Expected value: 0.836127, returned value from execution: 0.83612736.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromTonneForce.json**
Unit test set: FromTonneForce. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromTonneForce(Double tonnesForce).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:58:57
			Data returned for output 0 is different than expected.
			Expected value: 9806.65002864, returned value from execution: 9806.65.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromUSGallon.json**
Unit test set: FromUSGallon. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromUSGallon(Double usGallons).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:58:58
			Data returned for output 0 is different than expected.
			Expected value: 0.00378541, returned value from execution: 0.003785411784.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToImperialGallon.json**
Unit test set: ToImperialGallon. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToImperialGallon(Double cubicMetres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:58:59
			Data returned for output 0 is different than expected.
			Expected value: 219.969248299, returned value from execution: 219.969248299088.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToKilogramForce.json**
Unit test set: ToKilogramForce. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToKilogramForce(Double newtons).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:58:59
			Data returned for output 0 is different than expected.
			Expected value: 0.101971620999988, returned value from execution: 0.101971621297793.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToMile.json**
Unit test set: ToMile. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToMile(Double metres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:59:00
			Data returned for output 0 is different than expected.
			Expected value: 0.000621372736649807, returned value from execution: 0.000621371192237334.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToSquareMile.json**
Unit test set: ToSquareMile. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToSquareMile(Double squareMetres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:59:01
			Data returned for output 0 is different than expected.
			Expected value: 3.86100386100386E-07, returned value from execution: 3.86102158542446E-07.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToSquareYard.json**
Unit test set: ToSquareYard. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToSquareYard(Double squareMetres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:59:01
			Data returned for output 0 is different than expected.
			Expected value: 1.19599056124249, returned value from execution: 1.19599004630108.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToUSGallon.json**
Unit test set: ToUSGallon. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToUSGallon(Double cubicMetres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			26/04/2024 03:59:01
			Data returned for output 0 is different than expected.
			Expected value: 264.172176857989, returned value from execution: 264.172052358148.
</samp>

### LINKED ISSUE #123: An error occurred on a unit test
<samp>The following errors have been reported on unit tests in this repository.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromAcre.json**
Unit test set: FromAcre. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromAcre(Double acres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:47
			Data returned for output 0 is different than expected.
			Expected value: 4046.85642, returned value from execution: 4046.8564224.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromKilogramForce.json**
Unit test set: FromKilogramForce. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromKilogramForce(Double kilogramsForce).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:48
			Data returned for output 0 is different than expected.
			Expected value: 9.80665002864, returned value from execution: 9.80665.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromKilopoundForce.json**
Unit test set: FromKilopoundForce. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromKilopoundForce(Double kilopoundsForce).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:49
			Data returned for output 0 is different than expected.
			Expected value: 4448.22161526051, returned value from execution: 4448.2216152605.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromMile.json**
Unit test set: FromMile. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromMile(Double miles).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:49
			Data returned for output 0 is different than expected.
			Expected value: 1609.34, returned value from execution: 1609.344.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromSquareMile.json**
Unit test set: FromSquareMile. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromSquareMile(Double squareMiles).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:50
			Data returned for output 0 is different than expected.
			Expected value: 2590000, returned value from execution: 2589988.110336.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromSquareYard.json**
Unit test set: FromSquareYard. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromSquareYard(Double squareYards).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:50
			Data returned for output 0 is different than expected.
			Expected value: 0.836127, returned value from execution: 0.83612736.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromTonneForce.json**
Unit test set: FromTonneForce. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromTonneForce(Double tonnesForce).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:50
			Data returned for output 0 is different than expected.
			Expected value: 9806.65002864, returned value from execution: 9806.65.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\FromUSGallon.json**
Unit test set: FromUSGallon. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: FromUSGallon(Double usGallons).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:50
			Data returned for output 0 is different than expected.
			Expected value: 0.00378541, returned value from execution: 0.003785411784.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToImperialGallon.json**
Unit test set: ToImperialGallon. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToImperialGallon(Double cubicMetres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:51
			Data returned for output 0 is different than expected.
			Expected value: 219.969248299, returned value from execution: 219.969248299088.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToKilogramForce.json**
Unit test set: ToKilogramForce. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToKilogramForce(Double newtons).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:51
			Data returned for output 0 is different than expected.
			Expected value: 0.101971620999988, returned value from execution: 0.101971621297793.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToMile.json**
Unit test set: ToMile. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToMile(Double metres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:52
			Data returned for output 0 is different than expected.
			Expected value: 0.000621372736649807, returned value from execution: 0.000621371192237334.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToSquareMile.json**
Unit test set: ToSquareMile. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToSquareMile(Double squareMetres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:53
			Data returned for output 0 is different than expected.
			Expected value: 3.86100386100386E-07, returned value from execution: 3.86102158542446E-07.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToSquareYard.json**
Unit test set: ToSquareYard. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToSquareYard(Double squareMetres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:53
			Data returned for output 0 is different than expected.
			Expected value: 1.19599056124249, returned value from execution: 1.19599004630108.

**BHoM/Localisation_Toolkit\.ci\Datasets\Convert\ToUSGallon.json**
Unit test set: ToUSGallon. Author: Roly Hudson
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: ToUSGallon(Double cubicMetres).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			03/05/2024 03:56:54
			Data returned for output 0 is different than expected.
			Expected value: 264.172176857989, returned value from execution: 264.172052358148.
</samp>

### PR DESCRIPTION
**Pull request by albinber**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #123  

 

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by albinber** [comment]
@BHoMBot check unit-tests

**Comment by albinber** [comment]
@bhombot check required

**Comment by albinber** [comment]
@bhombot check compliance

**Comment by albinber** [comment]
@bhombot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Thanks for handling @albinber - @IsakNaslundBh and I will be happy not to get the nightly pings on this! 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
